# Generated by Django 4.2.1 on 2023-05-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contact_date_alter_course_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, default='nothing', max_length=100)),
                ('Email', models.CharField(default='nothing', max_length=100)),
                ('Place', models.CharField(blank=True, default='nothing', max_length=100)),
                ('Phone', models.CharField(blank=True, default='nothing', max_length=100)),
                ('Branch', models.CharField(blank=True, default='nothing', max_length=10)),
                ('date', models.DateField()),
            ],
        ),
    ]
